# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'newuser', 'verbose_name_plural': '\u666e\u901a\u7528\u6237newuser'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Poll', 'verbose_name_plural': '\u70b9\u8d5e'},
        ),
    ]
